version: '3.1'

services:
  db:
    build: ./Sql
    environment:
      MYSQL_ROOT_PASSWORD: somemdp
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - back-tier

  back:
    build: ./Back
    restart: always
    ports:
      - "8080:8080"
    environment:
      HOST_DB: db
      PORT: 8080
    networks:
      - back-tier
    depends_on:
      - db

  front:
    build: ./Front
    restart: always
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - back

networks:
  back-tier:

volumes:
  db-data: